apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-lanchonete
  labels:
    app: lanchonete  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lanchonete  
  template:
    metadata:
      labels:
        app: lanchonete  
    spec:
      containers:
        - name: lanchonete
          image: jordancodejp/pos-lanchonete:v1
          ports:
          - containerPort: 80
          env:
            - name: AUTHOR
              valueFrom:
                configMapKeyRef:
                  name: config-lanchonete
                  key: author
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-lanchonete
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-lanchonete
                  key: password   
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-lanchonete
                  key: dbhost
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-lanchonete
                  key: dbname  
            - name: PORT_NUMBER
              valueFrom:
                secretKeyRef:
                  name: secret-lanchonete
                  key: portnumber                    
          resources:
            requests:
              cpu: 80m
              memory: 70Mi
            limits:
              cpu: 120m
              memory: 140Mi                
---
apiVersion: v1
kind: Service
metadata:
  name: api-lanchonete-service
spec:
  type: NodePort
  selector:
    app: lanchonete 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-lanchonete
data:
  author: "Jordan"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-lanchonete
type: Opaque
data:
  username: cm1qb3JkYW4=
  password: ZmlhcEAyMDI1
  dbhost: c3Fsc2VydmVy
  dbname: TGFuY2hvbmV0ZQ==  
  portnumber: MTQzMw==
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-lanchonete
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-lanchonete
  targetCPUUtilizationPercentage: 50