apiVersion: v1
kind: Secret
metadata:
  name: secret-lanchonete-database
type: Opaque
data:
  MSSQL_SA_PASSWORD: ZmlhcEAyMDI1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  selector:
    matchLabels:
      app: mssql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql
        image: jordancodejp/server-2017-cu8-ubuntu-lanchonete:latest
        lifecycle:
          postStart:
            exec: 
              command: ["/bin/sh", "-c", "/var/tmp/run-script.sh"]        
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-lanchonete-database
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      nodePort: 30008
      port: 1433
      targetPort: 1433
  type: NodePort          